### ISSUE TITLE
Integrate into Android project

### ISSUE THREAD

**Issue by SmallRedSister** [kevashcraft/RoboFlash#1]
Hi! I feel that this project is very interesting. I would like to ask a question. I want to integrate this project into an existing Android project. What should I do?

**Comment by kevashcraft** [comment]
Depending on the other project (if it's native android or written in JS and wrapped) there may be more ways to include features into it, but the most universal would probably be the language data retrieval parts. To get those, take a look at the decks/decks.js file and consider how to use the json data that gets created during that process.
